### ISSUE TITLE
looks none working with solr 5 any more

### ISSUE THREAD

**Issue by frank-dspeed** [LucidWorks/solr-couchbase-plugin#3]
11.7.2015 20:53:35

ERROR

CoreContainer

Error creating core [dscms_shard1_replica1]: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'

org.apache.solr.common.SolrException: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:885)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:652)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:518)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:283)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:277)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:579)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:526)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:519)
    at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:571)
    at org.apache.solr.core.PluginBag.createPlugin(PluginBag.java:108)
    at org.apache.solr.core.PluginBag.init(PluginBag.java:203)
    at org.apache.solr.core.RequestHandlers.initHandlersFromConfig(RequestHandlers.java:130)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:808)
    ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:571)
    ... 15 more
Caused by: java.lang.NoClassDefFoundError: org/codehaus/jackson/map/ObjectMapper
    at org.apache.solr.couchbase.CouchbaseRequestHandler.<init>(CouchbaseRequestHandler.java:76)
    ... 20 more

11.7.2015 20:53:35

ERROR

CoreContainer

Error creating core [videodb_shard1_replica1]: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'

org.apache.solr.common.SolrException: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:885)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:652)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:518)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:283)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:277)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:579)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:526)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:519)
    at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:571)
    at org.apache.solr.core.PluginBag.createPlugin(PluginBag.java:108)
    at org.apache.solr.core.PluginBag.init(PluginBag.java:203)
    at org.apache.solr.core.RequestHandlers.initHandlersFromConfig(RequestHandlers.java:130)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:808)
    ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:571)
    ... 15 more
Caused by: java.lang.NoClassDefFoundError: org/codehaus/jackson/map/ObjectMapper
    at org.apache.solr.couchbase.CouchbaseRequestHandler.<init>(CouchbaseRequestHandler.java:76)
    ... 20 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.map.ObjectMapper
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 21 more

11.7.2015 20:53:35

ERROR

CoreContainer

Error creating core [dscmsConfig_shard1_replica1]: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'

org.apache.solr.common.SolrException: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:885)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:652)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:518)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:283)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:277)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Error instantiating class: 'org.apache.solr.couchbase.CouchbaseRequestHandler'
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:579)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:526)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:519)
    at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:571)
    at org.apache.solr.core.PluginBag.createPlugin(PluginBag.java:108)
    at org.apache.solr.core.PluginBag.init(PluginBag.java:203)
    at org.apache.solr.core.RequestHandlers.initHandlersFromConfig(RequestHandlers.java:130)
    at org.apache.solr.core.SolrCore.<init>(SolrCore.java:808)
    ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:571)
    ... 15 more
Caused by: java.lang.NoClassDefFoundError: org/codehaus/jackson/map/ObjectMapper
    at org.apache.solr.couchbase.CouchbaseRequestHandler.<init>(CouchbaseRequestHandler.java:76)
    ... 20 more

**Comment by frank-dspeed** [comment]
sorry was missing lib in war file can be closed
